name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Automated tests
      id: automated-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Automated tests
        setup-command: npm install
        command: npm test
        timeout: 10
        max-score: 9
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        AUTOMATED-TESTS_RESULTS: "${{steps.automated-tests.outputs.result}}"
      with:
        runners: automated-tests
